import Head from 'next/head'
import { Inter } from 'next/font/google'
import HomeComponents from '../components/Home/HomeComponents'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>{`AHMAD'S Trip`}</title> {/* Use curly braces and template literal */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeComponents />
    </>
  )
}
